
AllCops:
  SuggestExtensions: false

Metrics/AbcSize:
  Max: 30

Lint/AmbiguousBlockAssociation:
  Exclude:
  - spec/**/*

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']

Metrics/MethodLength:
  Max: 20
  CountComments: false

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false
